"""Personas (character files) and the renderer that turns events into lines.

Principle: humour lives in the delivery, never in the data. Every fact comes from
the event through ``{slots}``; the Fact guard checks that a line still carries them.
"""

from __future__ import annotations

import random
import string
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from .events import GameEvent
from .normaliser import Mode

# Facts that a line for this event kind MUST mention. Used to validate persona files
# and, later, to guard lines generated by a language model.
REQUIRED_FACTS: dict[str, tuple[str, ...]] = {
    "fsd_jump": ("system",),
    "docking_granted": ("pad",),
    "hull_damage": ("hull_pct",),
}

# Neutral fallback lines, used when a persona has nothing for an event kind.
DEFAULT_LINES: dict[str, str] = {
    "session_start": "Systems online, {address}.",
    "fsd_jump": "Arrived in {system}.",
    "docking_granted": "Docking granted, pad {pad}.",
    "docking_denied": "Docking denied: {reason}.",
    "docked": "Docked at {station}.",
    "undocked": "Clear of the station.",
    "interdiction": "Interdiction attempt!",
    "interdicted": "We've been pulled out of supercruise.",
    "interdiction_escaped": "Interdiction evaded.",
    "shields_down": "Shields down!",
    "shields_up": "Shields back online.",
    "hull_damage": "Hull at {hull_pct} percent.",
    "overheating": "Overheating!",
    "low_fuel": "Fuel low.",
    "fuel_scoop_done": "Fuel scooping complete.",
    "mission_completed": "Mission complete.",
    "combat_start": "Hostiles engaged.",
    "combat_end": "Combat over.",
    "died": "Rebuy screen, {address}.",
}

_FORMATTER = string.Formatter()


class _Facts(dict):
    """Leaves unknown slots visible instead of raising, so a missing fact is obvious."""

    def __missing__(self, key: str) -> str:
        return "{" + key + "}"


def slots_in(template: str) -> set[str]:
    return {name for _, name, _, _ in _FORMATTER.parse(template) if name}


@dataclass
class Persona:
    id: str
    name: str
    archetype: str
    description: str = ""
    address: str = "Commander"
    traits: dict[str, float] = field(default_factory=dict)
    voice: dict[str, Any] = field(default_factory=dict)
    style_prompt: str = ""
    cooldowns: dict[str, float] = field(default_factory=dict)
    lines: dict[str, list[str]] = field(default_factory=dict)
    combat_lines: dict[str, list[str]] = field(default_factory=dict)

    @property
    def chattiness(self) -> float:
        return float(self.traits.get("chattiness", 0.5))

    @classmethod
    def load(cls, path: str | Path) -> "Persona":
        data = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
        return cls(
            id=data["id"],
            name=data["name"],
            archetype=data.get("archetype", ""),
            description=data.get("description", ""),
            address=data.get("address_commander_as", "Commander"),
            traits=data.get("traits", {}) or {},
            voice=data.get("voice", {}) or {},
            style_prompt=data.get("style_prompt", ""),
            cooldowns=data.get("cooldowns", {}) or {},
            lines=data.get("lines", {}) or {},
            combat_lines=data.get("combat_lines", {}) or {},
        )

    def lines_for(self, kind: str, mode: str) -> list[str]:
        if mode == Mode.COMBAT and self.combat_lines.get(kind):
            return self.combat_lines[kind]
        return self.lines.get(kind, [])

    def validate(self) -> list[str]:
        """Return a list of problems; empty means the persona is fine."""
        problems: list[str] = []
        for section_name, section in (("lines", self.lines), ("combat_lines", self.combat_lines)):
            for kind, templates in section.items():
                if not isinstance(templates, list) or not templates:
                    problems.append(f"{section_name}.{kind}: must be a non-empty list")
                    continue
                for t in templates:
                    missing = set(REQUIRED_FACTS.get(kind, ())) - slots_in(t)
                    if missing:
                        problems.append(
                            f"{section_name}.{kind}: line {t!r} must mention {sorted(missing)}")
        c = self.chattiness
        if not 0.0 <= c <= 1.0:
            problems.append(f"traits.chattiness must be between 0 and 1 (got {c})")
        return problems


def fact_guard(text: str, event: GameEvent) -> bool:
    """True if ``text`` carries every required fact of ``event`` verbatim."""
    for key in REQUIRED_FACTS.get(event.kind, ()):
        if key in event.facts and str(event.facts[key]) not in text:
            return False
    return True


class Renderer:
    def __init__(self, persona: Persona, rng: random.Random | None = None, memory: int = 3):
        self.persona = persona
        self.rng = rng or random.Random()
        self._recent: dict[str, deque[str]] = {}
        self._memory = memory

    def render(self, event: GameEvent, mode: str) -> str | None:
        facts = _Facts({"address": self.persona.address, **event.facts})
        # Only lines whose every slot we can fill: an optional fact (ship name,
        # reward…) may be missing from a given Journal entry.
        templates = [t for t in self.persona.lines_for(event.kind, mode)
                     if slots_in(t) <= facts.keys()]
        if not templates:
            fallback = DEFAULT_LINES.get(event.kind)
            if fallback is None:
                return None
            templates = [fallback]
        recent = self._recent.setdefault(event.kind, deque(maxlen=self._memory))
        # Avoid the last few lines, but always leave at least one candidate.
        avoid = list(recent)[-(len(templates) - 1):] if len(templates) > 1 else []
        fresh = [t for t in templates if t not in avoid] or templates
        template = self.rng.choice(fresh)
        recent.append(template)
        text = template.format_map(facts)
        if not fact_guard(text, event):
            # Should not happen with validated personas; never let a wrong fact through.
            text = DEFAULT_LINES.get(event.kind, "").format_map(facts)
        return text
